### ISSUE TITLE
v7.16.1 - FB.LogInWithReadPermissions isn't calling callback in iOS9?

### ISSUE THREAD

**Issue by matatabi-ux** [facebook/facebook-sdk-for-unity#265]
I'm trying to use v7.16.1 in iOS and Android.
However, FB.LogInWithReadPermissions didn't call a callback in one case on the below.

**Not work:**
Facebook SDK v7.16.1 with Unity 2018.4.2f1
* iPhone 5, iOS 9.3.2

**Work completely:**
Facebook SDK v7.15.1 with Unity 2018.4.2f1
* iPhone 5, iOS 9.3.2

Facebook SDK v7.16.1 with Unity 2018.4.2f1
* iPhone X, iOS 12.3.1 
* Pixel 3a, Android 10 beta4
* Fujitsu F-10D Android 4.2.2

I tried to set a breakpoint at line 130 of FBUnityInterface.mm on Xcode.
However, it didn't break by running for debug in iPnone 5 with iOS 9.3.2.
The other iOS cases on the above, it breaked.

https://github.com/facebook/facebook-sdk-for-unity/blob/master/UnitySDK/Assets/FacebookSDK/SDK/Editor/iOS/FBUnityInterface.mm#L130

**Comment by sathyarajshetigar** [comment]
The issue exists in ios 10.1.1(14B100) as well

**Comment by korbul** [comment]
Same issue here. Anyone knows how to fix this? my objective C is rusty at best

**Comment by IneOtherGuys** [comment]
Same here, version v7.16.1. I get no callback from the login process FB.LogInWithReadPermissions, in iOS.  Working fine in Android.

**Comment by svennnni** [comment]
Is anyone fixing this on the Facebook side? Still occurring in Unity 7.17.1 in combination with iOS 5.2.1. 

Seems updating the Facebook SDK to include these strongly advertised, fundamental changes with respect to user privacy should not really be implemented in Unity apps...

**Comment by tayl0r** [comment]
You guys should be putting in these bugs in the Facebook developer site. FB doesn't really monitor this.

**Comment by svennnni** [comment]
> You guys should be putting in these bugs in the Facebook developer site. FB doesn't really monitor this.

Okay, thanks a lot for this suggestion. Did not expect that they have enabled the Issues functionality in their own GitHub repository but do not monitor it... Will try it in their developer pages...

**Comment by catdawg** [comment]
Here's the related bug in developer.facebook.com https://developers.facebook.com/support/bugs/2333800540030397/

**Comment by jbourne23** [comment]
> Here's the related bug in developer.facebook.com https://developers.facebook.com/support/bugs/2333800540030397/

We are having the same problem, it is not received in callback of the function FB.LogInWithReadPermissions for Unity / iOS. It seems incredible that the open bug appears as closed. We have tested in different versions and passes in all versions from 7.16.0 to 7.17.1

**Comment by svennnni** [comment]
There is an iOS update to version 5.2.3, which fixes this issue. I tested Unity SDK 7.17.1 in combination with iOS SDK 5.2.3 frameworks FBSDKCoreKit, FBSDKLoginKit, FBSDKShareKit. I tested it successfully with iOS 9.

**Comment by KylinChang** [comment]
The issue is in iOS SDK and the issue should be fixed. In v7.17.1 or v7.17.2, you can just re-run pod command to get the FB iOS SDK to fix the issue.

**Comment by vfilho** [comment]
This is still happening on v7.17.2

**Comment by KylinChang** [comment]
Hey @vfilho , what's your FB iOS SDK version after exporting the project?

**Comment by vfilho** [comment]
Sorry for the delay.
The version is 5.2 and I'm using the Appodel plugin to.

**Comment by vfilho** [comment]
Hi @KylinChang any update about this error, I already updated all plugins of my project, tried many facebook sdk versions and the problem persists.

**Comment by svennnni** [comment]
Unity SDK 7.17.2 in combination with iOS 5.2.3 is working, as written above. We have it in production with no problems (for this issue). It might be best to manually copy the respective iOS SDKs and not use the iOS Resolver to know exactly what is going on...

**Comment by vfilho** [comment]
Ok, i will try that @svennnni and let you know the results. Thanks.
