### ISSUE TITLE
v7.17.0 does not download binaries and libraries

### ISSUE THREAD

**Issue by steve-ddigital** [facebook/facebook-sdk-for-unity#274]
I have just installed FB SDK 7.17.0 into a Unity 2018.3.7 project that has Android and iOS build targets.  It fails to build on iOS because it cannot link to Bolts (for starters), and there is an error thrown during launch on Android that it cannot find the AppLinks class.

I noticed that a recent commit removed the binaries and libraries in favour of using Cocoapods and Maven.  I'm not sure what trickery is now required to get the binaries, but it does not download the binaries and libraries, neither in a local build (ld: library not found for -lBolts) or in a Unity Cloud Build (many internal errors).

I'm going to try downgrading to 7.16.1 to see if I can get this project building again.

**Comment by dreamolight** [comment]
Hi @steve-ddigital , could you try to run `pod install` command in the directory of generated Xcode project and share error log? Also, you'll need to open .xcworkspace file for the project instead of .xcodeproj file.

**Comment by steve-ddigital** [comment]
I could, but I'm already downgrading.  And that's not going to work on Unity Cloud Build.

**Comment by steve-ddigital** [comment]
Hi @dreamolight .  I'm doing the downgrade on my Windows PC, so i ran `pod install` on the existing Xcode project on the Mac.  I get `-bash: pod: command not found`

**Comment by steve-ddigital** [comment]
After the downgrade to 7.16.1, iOS and Android build and run with no errors.

**Comment by studentutu** [comment]
@steve-ddigital  @dreamolight  - 7.17 has a duplicates libraries for Unity (under Plugins/IOS and Andriod)
they cause all of the problems. To fix it we need to wait until they will release a fix (we don't know which of the libs requires frameworks for IOS!)

**Comment by Eirienen** [comment]
> 7.17 has a duplicates libraries for Unity (under Plugins/IOS and Andriod)

Same problem in my project.

**Comment by steve-ddigital** [comment]
The binaries need to be set for platforms.  This was something I had to fix in 7.17.0 as well.  It is not an issue in 7.16.1.  Select the DLLs in the project view, uncheck Any Platform and make sure the required platform (iOS or Android depending on which Plugins folder you're in) is checked.
![image](https://user-images.githubusercontent.com/39473066/60552819-ae257100-9d73-11e9-8da5-d1935a3821e0.png)

**Comment by iMagesBlues** [comment]
Mine compiles without errors (using Unity 2017.2.6) but FB.init crashes on Android.

**Comment by rcohendw** [comment]
Related:
https://github.com/facebook/facebook-sdk-for-unity/issues/282

**Comment by KylinChang** [comment]
The issue should be fixed in v7.17.2. @steve-ddigital , you should install cocoapods before running `pod install`: https://guides.cocoapods.org/using/getting-started.html

**Comment by steve-ddigital** [comment]
> you should install cocoapods before running

Our project using the Facebook SDK has finished development, so I won't be able to test this soon.  Do you know if Unity Cloud Build has cocoapods installed?  If not, then requiring it is not the best way forward.

**Comment by KylinChang** [comment]
Hi @steve-ddigital , Unity Cloud Build should have cocoapods installed: https://forum.unity.com/threads/solved-using-cocoapods-with-cloud-build.551551/

**Comment by chico-barnstorm** [comment]
I am afraid we are still experiencing this same issue:
- Facebook SDK v7.18.0 (we've also tried v7.17.2)
- MacBook Pro, running macOS 10.14.6
- XCode 11.1
- Cocoapods (manually installed, didn't download it automatically) version 1.8.4
- Unity 2018.4.12f1
XCode project created successfully but doesn't build because of missing libraries, such as:
`Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityUtility.h:19:9: 'FBSDKShareKit/FBSDKShareKit.h' file not found
Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityInterface.mm:21:9: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found
`
**Plus**, Unity Cloud Builds had been working fine until last Friday, now we are getting the following errors:
`Compiling _FBSDKTemporaryErrorRecoveryAttempter.m
503: ❌;  /BUILD_PATH/our_project.facebook-sdk/temp.XXXXXX20191111-5173-17ey36x/Frameworks/FacebookSDK/Plugins/iOS/FBSDKCoreKit.framework/Headers/FBSDKCoreKit.h:23:9:
504: ❌;  fatal error: could not build module 'FBSDKCoreKit'`

Any clues? Anyone having the same issue(s)?

**Comment by chico-barnstorm** [comment]
> @KylinChang, I am afraid we are still experiencing this same issue:
> 
> * Facebook SDK v7.18.0 (we've also tried v7.17.2)
> * MacBook Pro, running macOS 10.14.6
> * XCode 11.1
> * Cocoapods (manually installed, didn't download it automatically) version 1.8.4
> * Unity 2018.4.12f1
>   XCode project created successfully but doesn't build because of missing libraries, such as:
>   `Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityUtility.h:19:9: 'FBSDKShareKit/FBSDKShareKit.h' file not found Libraries/FacebookSDK/SDK/Editor/iOS/FBUnityInterface.mm:21:9: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found `
>   **Plus**, Unity Cloud Builds had been working fine until last Friday, now we are getting the following errors:
>   `Compiling _FBSDKTemporaryErrorRecoveryAttempter.m 503: ❌;  /BUILD_PATH/our_project.facebook-sdk/temp.XXXXXX20191111-5173-17ey36x/Frameworks/FacebookSDK/Plugins/iOS/FBSDKCoreKit.framework/Headers/FBSDKCoreKit.h:23:9: 504: ❌;  fatal error: could not build module 'FBSDKCoreKit'`
> 
> Any clues? Anyone having the same issue(s)?

Cocoapods still doesn't seem to download the files, but at least we managed to fix the **cloud builds** as described [here](http://answers.unity.com/answers/1677577/view.html).
