### ISSUE TITLE
Facebook SDK 7.9.0 seems to break build with 7.x XCode

### ISSUE THREAD

**Issue by vertti** [facebook/facebook-sdk-for-unity#41]
Upgrading from 7.8.0 to 7.9.0 fails the XCode build with 7.3.1 xcode and gives me error 

```
14425:        [xcode] error: Invalid bitcode version (Producer: '800.0.38.0_0' Reader: '703.0.31_0')
14426:        [xcode] clang: error: linker command failed with exit code 1 (use -v to see invocation)
14427:        [xcode] ** BUILD FAILED **
```

Building with Unity v5.4.2f2 on Cloud build.

**Comment by VinceFior** [comment]
Hi Janne. We build our SDK releases with the latest version of Xcode, and 7.9.0 was built with Xcode 8. We recommend upgrading to Xcode 8, which should fix this issue.

**Comment by vertti** [comment]
We use Unity Cloud Build which unfortunately does not (yet) support Xcode 8.

**Comment by VinceFior** [comment]
Ah, I see. In that case, I think the best option is to disable bitcode. To do so, go to your Build Options and set "Enable Bitcode" to "NO".

**Comment by 00christian00** [comment]
Isn't the sdk open source anymore? Here on Github I still see 7.8.

**Comment by VinceFior** [comment]
Hi Christian. Version 7.9.0 is now available here on GitHub. We release new versions of the SDK on our [developer site](https://developers.facebook.com/docs/unity/) in addition to GitHub, and this time we released version 7.9.0 on the developer site a few days before GitHub. Sorry for the confusion!
